export interface Module {
  id: string;
  title: string;
  titleEn: string;
  description: string;
  descriptionEn: string;
  isFree: boolean;
  order: number;
  duration: string;
}

export interface Course {
  id: string;
  slug: string;
  category?: string;
  title: string;
  titleEn: string;
  description: string;
  descriptionEn: string;
  longDescription: string;
  longDescriptionEn: string;
  level: 1 | 2 | 3;
  price: number;
  modules: Module[];
  image: string;
  tags: string[];
  competences?: string[];
  public_cible?: string;
  prerequis?: string;
  duree_heures?: number;
}

export const courses: Course[] = [
  {
    id: 'sec-fundamentals',
    slug: 'securite-fondamentaux',
    category: 'cybersecurite',
    title: 'Securite informatique - Les fondamentaux',
    titleEn: 'IT Security - Fundamentals',
    description: 'Maitrisez les bases de la securite informatique et comprennez les menaces actuelles',
    descriptionEn: 'Master the basics of IT security and understand current threats',
    longDescription: "Cette formation vous donnera une vision complete des fondamentaux de la securite informatique. Vous apprendrez a identifier les menaces, comprendre les vecteurs d'attaque et mettre en place des mesures de protection efficaces. Ideal pour debuter dans la cybersecurity.",
    longDescriptionEn: 'This training will give you a complete overview of IT security fundamentals. You will learn to identify threats, understand attack vectors, and implement effective protection measures. Ideal for starting in cybersecurity.',
    level: 1,
    price: 49,
    image: 'https://images.pexels.com/photos/60504/security-hacker-black-background-60504.jpeg?w=800',
    tags: ['securite', 'reseaux', 'debutant'],
    modules: [
      { id: 'mod-0', title: 'Introduction a la securite', titleEn: 'Introduction to Security', description: 'Vue densemble du paysage de la securite informatique', descriptionEn: 'Overview of the IT security landscape', isFree: true, order: 0, duration: '30min' },
      { id: 'mod-1', title: 'Types de menaces', titleEn: 'Types of Threats', description: 'Malwares, phishing, ingenierie sociale et plus', descriptionEn: 'Malware, phishing, social engineering and more', isFree: false, order: 1, duration: '45min' },
      { id: 'mod-2', title: 'Reconnaissance reseau', titleEn: 'Network Reconnaissance', description: 'Comprendre TCP/IP et les protocoles reseau', descriptionEn: 'Understanding TCP/IP and network protocols', isFree: false, order: 2, duration: '1h' },
      { id: 'mod-3', title: 'Securite des mots de passe', titleEn: 'Password Security', description: 'Hachage, salage et bonnes pratiques', descriptionEn: 'Hashing, salting and best practices', isFree: false, order: 3, duration: '45min' },
      { id: 'mod-4', title: 'Introduction au chiffrement', titleEn: 'Introduction to Encryption', description: 'Symetrique, asymetrique et PKI', descriptionEn: 'Symmetric, asymmetric and PKI', isFree: false, order: 4, duration: '1h' },
    ]
  },
  {
    id: 'network-security',
    slug: 'securisation-reseaux',
    category: 'cybersecurite',
    title: 'Securisation des reseaux dentreprise',
    titleEn: 'Enterprise Network Security',
    description: 'Concevez et securisez des infrastructures reseau professionnelles',
    descriptionEn: 'Design and secure professional network infrastructures',
    longDescription: "Plongez dans la securite reseau avancee. Cette formation couvre les pare-feux, les IDS/IPS, la segmentation reseau et les architectures Zero Trust. Pret pour des environnements d'entreprise.",
    longDescriptionEn: 'Dive into advanced network security. This training covers firewalls, IDS/IPS, network segmentation, and Zero Trust architectures. Ready for enterprise environments.',
    level: 2,
    price: 89,
    image: 'https://images.pexels.com/photos/114882/pexels-photo-114882.jpeg?w=800',
    tags: ['reseaux', 'firewall', 'infrastructure'],
    modules: [
      { id: 'mod-0', title: 'Architecture reseau securisee', titleEn: 'Secure Network Architecture', description: 'Principes de conception et zones de confiance', descriptionEn: 'Design principles and trust zones', isFree: true, order: 0, duration: '45min' },
      { id: 'mod-1', title: 'Configuration des pare-feux', titleEn: 'Firewall Configuration', description: 'Regles, politiques et bonnes pratiques', descriptionEn: 'Rules, policies and best practices', isFree: false, order: 1, duration: '1h30' },
      { id: 'mod-2', title: 'IDS et IPS', titleEn: 'IDS and IPS', description: "Detection et prevention d'intrusion", descriptionEn: 'Intrusion Detection and Prevention', isFree: false, order: 2, duration: '1h' },
      { id: 'mod-3', title: 'Segmentation et VLANs', titleEn: 'Segmentation and VLANs', description: 'Isolation et controle du trafic', descriptionEn: 'Isolation and traffic control', isFree: false, order: 3, duration: '1h' },
      { id: 'mod-4', title: 'VPN et tunnels securises', titleEn: 'VPN and Secure Tunnels', description: 'IPSec, OpenVPN et WireGuard', descriptionEn: 'IPSec, OpenVPN and WireGuard', isFree: false, order: 4, duration: '1h30' },
      { id: 'mod-5', title: 'Architecture Zero Trust', titleEn: 'Zero Trust Architecture', description: 'Mise en oeuvre pratique', descriptionEn: 'Practical implementation', isFree: false, order: 5, duration: '1h' },
    ]
  },
  {
    id: 'web-pentest',
    slug: 'pentest-web',
    category: 'cybersecurite',
    title: 'Pentesting Web - Debutant a Expert',
    titleEn: 'Web Pentesting - Beginner to Expert',
    description: 'Apprenez a identifier et exploiter les vulnerabilites web',
    descriptionEn: 'Learn to identify and exploit web vulnerabilities',
    longDescription: "Devenir un expert en penetration testing web. Maitrisez OWASP Top 10, les outils professionnels et les techniques d'exploitation avancees. Labs pratiques sur des environnements dedies.",
    longDescriptionEn: 'Become an expert in web penetration testing. Master OWASP Top 10, professional tools, and advanced exploitation techniques. Practical labs on dedicated environments.',
    level: 3,
    price: 149,
    image: 'https://images.pexels.com/photos/5380643/pexels-photo-5380643.jpeg?w=800',
    tags: ['pentest', 'web', 'exploitation'],
    modules: [
      { id: 'mod-0', title: 'Methodologie du pentest', titleEn: 'Pentest Methodology', description: "Cycle de vie d'un audit de securite", descriptionEn: 'Security audit lifecycle', isFree: true, order: 0, duration: '45min' },
      { id: 'mod-1', title: 'OWASP Top 10 en detail', titleEn: 'OWASP Top 10 in Detail', description: 'Anatomie des vulnerabilites web critiques', descriptionEn: 'Anatomy of critical web vulnerabilities', isFree: false, order: 1, duration: '2h' },
      { id: 'mod-2', title: 'SQL Injection avancee', titleEn: 'Advanced SQL Injection', description: "Techniques d'injection et bypass", descriptionEn: 'Injection and bypass techniques', isFree: false, order: 2, duration: '1h30' },
      { id: 'mod-3', title: 'XSS et CSRF', titleEn: 'XSS and CSRF', description: 'Cross-site scripting et request forgery', descriptionEn: 'Cross-site scripting and request forgery', isFree: false, order: 3, duration: '1h30' },
      { id: 'mod-4', title: 'Outils Burp Suite', titleEn: 'Burp Suite Tools', description: 'Maitrise de la suite Burp', descriptionEn: 'Mastering Burp Suite', isFree: false, order: 4, duration: '2h' },
      { id: 'mod-5', title: 'Reporting professionnel', titleEn: 'Professional Reporting', description: "Redaction de rapports d'audit", descriptionEn: 'Writing audit reports', isFree: false, order: 5, duration: '1h' },
    ]
  },
  {
    id: 'linux-security',
    slug: 'linux-securite',
    category: 'cybersecurite',
    title: 'Administration Linux securisee',
    titleEn: 'Secure Linux Administration',
    description: 'Maitrisez la securite des systemes Linux en environnement professionnel',
    descriptionEn: 'Master Linux system security in professional environments',
    longDescription: "Formation complete a l'administration securisee de Linux. Hardening systeme, gestion des utilisateurs, SELinux, conteneurisation securisee et surveillance.",
    longDescriptionEn: 'Complete training in secure Linux administration. System hardening, user management, SELinux, secure containerization, and monitoring.',
    level: 2,
    price: 89,
    image: 'https://images.pexels.com/photos/1089440/pexels-photo-1089440.jpeg?w=800',
    tags: ['linux', 'administration', 'hardening'],
    modules: [
      { id: 'mod-0', title: 'Introduction a Linux', titleEn: 'Introduction to Linux', description: 'Environnement et commandes de base', descriptionEn: 'Environment and basic commands', isFree: true, order: 0, duration: '45min' },
      { id: 'mod-1', title: 'Hardening du systeme', titleEn: 'System Hardening', description: 'Configurations securisees et services', descriptionEn: 'Secure configurations and services', isFree: false, order: 1, duration: '1h30' },
      { id: 'mod-2', title: 'Gestion des utilisateurs', titleEn: 'User Management', description: 'Permissions, sudo et PAM', descriptionEn: 'Permissions, sudo and PAM', isFree: false, order: 2, duration: '1h' },
      { id: 'mod-3', title: 'SELinux et AppArmor', titleEn: 'SELinux and AppArmor', description: "Controle d'acces mandataire", descriptionEn: 'Mandatory Access Control', isFree: false, order: 3, duration: '1h30' },
      { id: 'mod-4', title: 'Logs et surveillance', titleEn: 'Logs and Monitoring', description: 'Audit, journald et SIEM', descriptionEn: 'Audit, journald and SIEM', isFree: false, order: 4, duration: '1h' },
    ]
  },
  {
    id: 'osint-course',
    slug: 'osint-techniques',
    category: 'cybersecurite',
    title: 'OSINT - Intelligence en sources ouvertes',
    titleEn: 'OSINT - Open Source Intelligence',
    description: "Techniques de collecte et analyse d'informations publiquement accessibles",
    descriptionEn: 'Techniques for collecting and analyzing publicly accessible information',
    longDescription: "Maitrisez l'art de l'intelligence en sources ouvertes. Outils de reconnaissance, techniques d'investigation numerique, analyse de metadonnees et footprinting.",
    longDescriptionEn: 'Master the art of open source intelligence. Reconnaissance tools, digital investigation techniques, metadata analysis, and footprinting.',
    level: 2,
    price: 89,
    image: 'https://images.pexels.com/photos/5380643/pexels-photo-5380643.jpeg?w=800',
    tags: ['osint', 'investigation', 'reconnaissance'],
    modules: [
      { id: 'mod-0', title: "Introduction a l'OSINT", titleEn: 'Introduction to OSINT', description: 'Principes et cadre legal', descriptionEn: 'Principles and legal framework', isFree: true, order: 0, duration: '30min' },
      { id: 'mod-1', title: 'Recherche avancee', titleEn: 'Advanced Search', description: 'Google dorks et moteurs specialises', descriptionEn: 'Google dorks and specialized engines', isFree: false, order: 1, duration: '1h' },
      { id: 'mod-2', title: 'Metadonnees et fichiers', titleEn: 'Metadata and Files', description: 'Exif, documents et traces numeriques', descriptionEn: 'Exif, documents and digital traces', isFree: false, order: 2, duration: '1h' },
      { id: 'mod-3', title: 'Reseaux sociaux', titleEn: 'Social Networks', description: 'Profiling et recoupement', descriptionEn: 'Profiling and cross-referencing', isFree: false, order: 3, duration: '1h30' },
      { id: 'mod-4', title: 'Outils OSINT', titleEn: 'OSINT Tools', description: 'Maltego, Shodan et autres', descriptionEn: 'Maltego, Shodan and others', isFree: false, order: 4, duration: '1h30' },
    ]
  },
  {
    id: 'malware-analysis',
    slug: 'analyse-malware',
    category: 'cybersecurite',
    title: 'Analyse de malwares - Niveau expert',
    titleEn: 'Malware Analysis - Expert Level',
    description: 'Analyse statique et dynamique de codes malveillants',
    descriptionEn: 'Static and dynamic analysis of malicious code',
    longDescription: "Plongez dans l'analyse de malwares. Techniques de sandboxing, desassemblage, ingenierie inverse et creation de signatures. Pour experts uniquement.",
    longDescriptionEn: 'Dive into malware analysis. Sandboxing techniques, disassembly, reverse engineering, and signature creation. Experts only.',
    level: 3,
    price: 149,
    image: 'https://images.pexels.com/photos/60504/security-hacker-black-background-60504.jpeg?w=800',
    tags: ['malware', 'reverse-engineering', 'analyse'],
    modules: [
      { id: 'mod-0', title: 'Types de malwares', titleEn: 'Types of Malware', description: 'Classification et comportements typiques', descriptionEn: 'Classification and typical behaviors', isFree: true, order: 0, duration: '45min' },
      { id: 'mod-1', title: 'Analyse statique', titleEn: 'Static Analysis', description: 'Strings, imports et indicateurs', descriptionEn: 'Strings, imports and indicators', isFree: false, order: 1, duration: '2h' },
      { id: 'mod-2', title: 'Analyse dynamique', titleEn: 'Dynamic Analysis', description: 'Sandboxing et surveillance systeme', descriptionEn: 'Sandboxing and system monitoring', isFree: false, order: 2, duration: '2h' },
      { id: 'mod-3', title: 'Desassemblage', titleEn: 'Disassembly', description: 'IDA Pro, Ghidra et assembleur', descriptionEn: 'IDA Pro, Ghidra and assembly', isFree: false, order: 3, duration: '2h' },
      { id: 'mod-4', title: 'Anti-analyse et bypass', titleEn: 'Anti-analysis and Bypass', description: "Techniques d'evasion et contournement", descriptionEn: 'Evasion techniques and bypassing', isFree: false, order: 4, duration: '2h' },
      { id: 'mod-5', title: 'Creation de signatures YARA', titleEn: 'YARA Signature Creation', description: 'Detection et partage', descriptionEn: 'Detection and sharing', isFree: false, order: 5, duration: '1h30' },
    ]
  },
  // ===== 13 NOUVELLES FORMATIONS CYBERSÉCURITÉ =====
  {
    id: 'cyber-intro',
    slug: 'introduction-cybersecurite',
    category: 'cybersecurite',
    title: 'Introduction à la Cybersécurité',
    titleEn: 'Introduction to Cybersecurity',
    description: 'Fondamentaux de la cybersécurité : menaces, vecteurs d\'attaque, protection quotidienne et bonnes pratiques pour naviguer en sécurité.',
    descriptionEN: 'Cybersecurity fundamentals: threats, attack vectors, daily protection and best practices for safe browsing.',
    longDescription: "Acquérir les fondamentaux de la cybersécurité et comprendre le paysage des menaces numériques. Ce cours pose les bases essentielles pour tout professionnel de l'informatique : concepts clés, vocabulaire, acteurs de la sécurité, et panorama des risques actuels.",
    longDescriptionEN: "Acquire the fundamentals of cybersecurity and understand the digital threat landscape. This course lays the essential foundations for any IT professional: key concepts, vocabulary, security actors, and panorama of current risks.",
    level: 1,
    price: 49,
    duree_heures: 20,
    image: 'https://images.pexels.com/photos/60504/security-hacker-black-background-60504.jpeg?w=800',
    tags: ['cybersecurite', 'fondamentaux', 'debutant', 'menaces'],
    competences: [
      "Identifier et catégoriser les principales menaces cyber (phishing, malware, ransomware, spam)",
      "Reconnaître une tentative d'hameçonnage et adopter les bons réflexes",
      "Comprendre les vecteurs d'attaque utilisés par les cybercriminels",
      "Sécuriser sa navigation Internet et vérifier la fiabilité d'un site web",
      "Protéger l'accès local à ses données (mots de passe, BIOS, sessions)",
      "Comprendre les enjeux d'anonymat et d'identification sur Internet",
      "Appliquer les bonnes pratiques de sécurité au quotidien",
      "Analyser des attaques réelles et leur impact sur les organisations"
    ],
    public_cible: 'Débutant',
    prerequis: 'Aucun – accessible à toute personne souhaitant découvrir la cybersécurité',
    modules: [
      { id: 'mod-0', title: 'Concepts fondamentaux de la cybersécurité et vocabulaire', titleEn: 'Fundamental concepts and vocabulary', description: 'Terminologie, acteurs et paysage de la cybersécurité', descriptionEn: 'Terminology, actors and cybersecurity landscape', isFree: true, order: 0, duration: '1h30' },
      { id: 'mod-1', title: 'Le périmètre et les acteurs de la sécurité des réseaux', titleEn: 'Scope and network security actors', description: 'Qui protège quoi et comment s\'organise la défense', descriptionEn: 'Who protects what and how defense is organized', isFree: false, order: 1, duration: '1h30' },
      { id: 'mod-2', title: 'L\'évolution des menaces – panorama des risques actuels', titleEn: 'Evolution of threats – current risk panorama', description: 'Les menaces modernes et leur progression', descriptionEn: 'Modern threats and their evolution', isFree: false, order: 2, duration: '1h30' },
      { id: 'mod-3', title: 'Les différents types de risques en cybersécurité', titleEn: 'Different types of cybersecurity risks', description: 'Phishing, spam, stealers, ransomware', descriptionEn: 'Phishing, spam, stealers, ransomware', isFree: false, order: 3, duration: '1h30' },
      { id: 'mod-4', title: 'Introduction aux malwares et vecteurs d\'attaque', titleEn: 'Introduction to malware and attack vectors', description: 'Comment les attaquants infectent les systèmes', descriptionEn: 'How attackers infect systems', isFree: false, order: 4, duration: '1h30' },
      { id: 'mod-5', title: 'Les attaques à distance et les intrusions', titleEn: 'Remote attacks and intrusions', description: 'White hat vs black hat', descriptionEn: 'White hat vs black hat', isFree: false, order: 5, duration: '1h30' },
      { id: 'mod-6', title: 'Vol de mots de passe et techniques de brute force', titleEn: 'Password theft and brute force techniques', description: 'Comment les mots de passe sont compromis', descriptionEn: 'How passwords are compromised', isFree: false, order: 6, duration: '1h30' },
      { id: 'mod-7', title: 'Sécuriser sa navigation sur Internet', titleEn: 'Securing web browsing', description: 'HTTPS, cookies, anonymat', descriptionEn: 'HTTPS, cookies, anonymity', isFree: false, order: 7, duration: '1h30' },
      { id: 'mod-8', title: 'Protection locale des données', titleEn: 'Local data protection', description: 'BIOS, Windows, comptes utilisateurs', descriptionEn: 'BIOS, Windows, user accounts', isFree: false, order: 8, duration: '1h30' },
      { id: 'mod-9', title: 'Identification sur Internet et protocole HTTPS', titleEn: 'Internet identification and HTTPS protocol', description: 'Certificats et confiance en ligne', descriptionEn: 'Certificates and online trust', isFree: false, order: 9, duration: '1h30' },
      { id: 'mod-10', title: 'Comment se protéger ? Antivirus, firewall, bonnes pratiques', titleEn: 'How to protect yourself? Antivirus, firewall, best practices', description: 'Stratégies de défense essentielles', descriptionEn: 'Essential defense strategies', isFree: false, order: 10, duration: '2h' },
    ]
  },
  {
    id: 'cyber-risques',
    slug: 'risques-menaces-informatique',
    category: 'cybersecurite',
    title: 'Risques et Menaces Informatiques',
    titleEn: 'IT Risks and Threats',
    description: 'Panorama complet des menaces informatiques : phishing, malwares, ransomware, ingénierie sociale et stratégies de défense.',
    descriptionEN: 'Complete panorama of IT threats: phishing, malware, ransomware, social engineering and defense strategies.',
    longDescription: "Approfondir la connaissance des menaces informatiques et des risques liés à la sécurité des systèmes d'information. L'apprenant apprendra à identifier, classifier et analyser les différents types d'attaques, ainsi qu'à comprendre les mécanismes de l'ingénierie sociale.",
    longDescriptionEN: "Deepen knowledge of IT threats and information security risks. Learners will identify, classify and analyze different types of attacks, and understand social engineering mechanisms.",
    level: 1,
    price: 59,
    duree_heures: 15,
    image: 'https://images.pexels.com/photos/5380643/pexels-photo-5380643.jpeg?w=800',
    tags: ['cybersecurite', 'menaces', 'phishing', 'ransomware'],
    competences: [
      "Identifier et classifier les différents types de menaces informatiques",
      "Détecter une tentative de phishing ou d'ingénierie sociale",
      "Comprendre le fonctionnement des malwares, stealers et ransomwares",
      "Réagir face à un incident de sécurité",
      "Analyser des attaques réelles et leur impact",
      "Sensibiliser les utilisateurs aux bonnes pratiques",
      "Mettre en place des mesures de prévention adaptées"
    ],
    public_cible: 'Débutant à intermédiaire',
    prerequis: 'Connaissances de base en informatique et réseaux',
    modules: [
      { id: 'mod-0', title: 'Panorama des menaces et attaques cyber', titleEn: 'Panorama of cyber threats and attacks', description: 'Vue d\'ensemble des menaces actuelles', descriptionEn: 'Overview of current threats', isFree: true, order: 0, duration: '1h30' },
      { id: 'mod-1', title: 'Le phishing – techniques, détection et réaction', titleEn: 'Phishing – techniques, detection and reaction', description: 'Reconnaître et contrer le hameçonnage', descriptionEn: 'Recognize and counter phishing', isFree: false, order: 1, duration: '1h30' },
      { id: 'mod-2', title: 'Les e-mails indésirables et dangereux', titleEn: 'Unwanted and dangerous emails', description: 'Spam, scams, bots', descriptionEn: 'Spam, scams, bots', isFree: false, order: 2, duration: '1h' },
      { id: 'mod-3', title: 'Les stealers et logiciels espions', titleEn: 'Stealers and spyware', description: 'Vol de données et surveillance', descriptionEn: 'Data theft and surveillance', isFree: false, order: 3, duration: '1h' },
      { id: 'mod-4', title: 'Les 5 vecteurs d\'attaque du ransomware', titleEn: 'The 5 ransomware attack vectors', description: 'Propagation et impact', descriptionEN: 'Propagation and impact', isFree: false, order: 4, duration: '1h30' },
      { id: 'mod-5', title: 'L\'ingénierie sociale – l\'arme fatale du hacker', titleEn: 'Social engineering – the hacker\'s ultimate weapon', description: 'Manipulation et tromperie', descriptionEN: 'Manipulation and deception', isFree: false, order: 5, duration: '1h30' },
      { id: 'mod-6', title: 'Introduction aux malwares – typologie et fonctionnement', titleEn: 'Introduction to malware – typology and operation', description: 'Classification et mécanismes', descriptionEN: 'Classification and mechanisms', isFree: false, order: 6, duration: '1h30' },
      { id: 'mod-7', title: 'Les incidents de sécurité – comment les gérer', titleEn: 'Security incidents – how to manage them', description: 'Procédures de réponse', descriptionEN: 'Response procedures', isFree: false, order: 7, duration: '1h' },
      { id: 'mod-8', title: 'Études de cas et travaux pratiques', titleEn: 'Case studies and practical exercises', description: 'Analyse d\'attaques réelles', descriptionEN: 'Real attack analysis', isFree: false, order: 8, duration: '2h' },
    ]
  },
  {
    id: 'cyber-navigateur',
    slug: 'securite-navigateur-web',
    category: 'cybersecurite',
    title: 'Sécurité des Navigateurs Web',
    titleEn: 'Web Browser Security',
    description: 'Sécurité et optimisation des navigateurs web : protocoles, vie privée, menaces et configuration sécurisée.',
    descriptionEN: 'Security and optimization of web browsers: protocols, privacy, threats and secure configuration.',
    longDescription: "Maîtriser les enjeux de sécurité liés aux navigateurs web, apprendre à optimiser et sécuriser son environnement de navigation. Comprendre les protocoles fondamentaux, les risques de pistage et les solutions de protection.",
    longDescriptionEN: "Master the security issues related to web browsers, learn to optimize and secure your browsing environment. Understand fundamental protocols, tracking risks and protection solutions.",
    level: 1,
    price: 39,
    duree_heures: 10,
    image: 'https://images.pexels.com/photos/114882/pexels-photo-114882.jpeg?w=800',
    tags: ['cybersecurite', 'navigateur', 'vie-privee', 'web'],
    competences: [
      "Comprendre le fonctionnement et l'architecture des navigateurs web",
      "Configurer et optimiser un navigateur pour la sécurité et la vie privée",
      "Identifier et bloquer les menaces web (phishing, trackers, publicités malveillantes)",
      "Utiliser des outils de navigation sécurisée (Brave, Tor, extensions)",
      "Vérifier les certificats SSL/TLS et la fiabilité des sites",
      "Maîtriser la gestion des cookies et des données de navigation"
    ],
    public_cible: 'Débutant',
    prerequis: 'Usage quotidien d\'Internet et d\'un navigateur web',
    modules: [
      { id: 'mod-0', title: 'Qu\'est-ce qu\'un navigateur Web ?', titleEn: 'What is a web browser?', description: 'Fonctionnement et architecture', descriptionEN: 'Operation and architecture', isFree: true, order: 0, duration: '1h' },
      { id: 'mod-1', title: 'Optimisation du navigateur', titleEn: 'Browser optimization', description: 'Mises à jour, extensions, cache, cookies', descriptionEN: 'Updates, extensions, cache, cookies', isFree: false, order: 1, duration: '1h' },
      { id: 'mod-2', title: 'Sécuriser sa navigation', titleEn: 'Securing your browsing', description: 'HTTPS, certificats, mots de passe', descriptionEN: 'HTTPS, certificates, passwords', isFree: false, order: 2, duration: '1h' },
      { id: 'mod-3', title: 'Les protocoles fondamentaux', titleEn: 'Fundamental protocols', description: 'IP, TCP, HTTPS/TLS', descriptionEN: 'IP, TCP, HTTPS/TLS', isFree: false, order: 3, duration: '1h' },
      { id: 'mod-4', title: 'Panorama des navigateurs', titleEn: 'Browser panorama', description: 'Chrome, Firefox, Edge, Opera, Brave', descriptionEN: 'Chrome, Firefox, Edge, Opera, Brave', isFree: false, order: 4, duration: '1h' },
      { id: 'mod-5', title: 'Vie privée et anonymat', titleEn: 'Privacy and anonymity', description: 'Tor, Brave Shields, anti-fingerprinting', descriptionEN: 'Tor, Brave Shields, anti-fingerprinting', isFree: false, order: 5, duration: '1h30' },
      { id: 'mod-6', title: 'Menaces web', titleEn: 'Web threats', description: 'Phishing, malvertising, drive-by download', descriptionEN: 'Phishing, malvertising, drive-by download', isFree: false, order: 6, duration: '1h30' },
      { id: 'mod-7', title: 'Bonnes pratiques et configuration sécurisée', titleEn: 'Best practices and secure configuration', description: 'Checklist de sécurité navigateur', descriptionEN: 'Browser security checklist', isFree: false, order: 7, duration: '1h' },
    ]
  },
  {
    id: 'cyber-crypto',
    slug: 'cryptographie-hashage',
    category: 'cybersecurite',
    title: 'Cryptographie et Hashage',
    titleEn: 'Cryptography and Hashing',
    description: 'Fondamentaux de la cryptographie : chiffrement, hashage, signatures numériques et protocoles de sécurité.',
    descriptionEN: 'Cryptography fundamentals: encryption, hashing, digital signatures and security protocols.',
    longDescription: "Comprendre les principes fondamentaux de la cryptographie et du hashage, essentiels pour sécuriser les données et les communications. Ce cours couvre les algorithmes de chiffrement, les fonctions de hachage et leurs applications concrètes en cybersécurité.",
    longDescriptionEN: "Understand the fundamental principles of cryptography and hashing, essential for securing data and communications. This course covers encryption algorithms, hash functions and their concrete applications in cybersecurity.",
    level: 2,
    price: 79,
    duree_heures: 15,
    image: 'https://images.pexels.com/photos/60504/security-hacker-black-background-60504.jpeg?w=800',
    tags: ['cybersecurite', 'cryptographie', 'chiffrement', 'securite'],
    competences: [
      "Comprendre les différences entre chiffrement symétrique et asymétrique",
      "Utiliser les fonctions de hachage pour vérifier l'intégrité des données",
      "Mettre en œuvre des signatures numériques et des certificats",
      "Analyser les protocoles cryptographiques utilisés dans les communications",
      "Appliquer la cryptographie pour sécuriser les données au repos et en transit",
      "Identifier les faiblesses des algorithmes obsolètes"
    ],
    public_cible: 'Intermédiaire',
    prerequis: 'Connaissances de base en informatique et mathématiques (binaire, logique)',
    modules: [
      { id: 'mod-0', title: 'Introduction à la cryptographie', titleEn: 'Introduction to cryptography', description: 'Histoire et principes', descriptionEN: 'History and principles', isFree: true, order: 0, duration: '1h30' },
      { id: 'mod-1', title: 'Chiffrement symétrique', titleEn: 'Symmetric encryption', description: 'AES, DES, 3DES', descriptionEN: 'AES, DES, 3DES', isFree: false, order: 1, duration: '1h30' },
      { id: 'mod-2', title: 'Chiffrement asymétrique', titleEn: 'Asymmetric encryption', description: 'RSA, ECC, PKI', descriptionEN: 'RSA, ECC, PKI', isFree: false, order: 2, duration: '2h' },
      { id: 'mod-3', title: 'Les fonctions de hachage', titleEn: 'Hash functions', description: 'MD5, SHA-1, SHA-256, bcrypt', descriptionEN: 'MD5, SHA-1, SHA-256, bcrypt', isFree: false, order: 3, duration: '1h30' },
      { id: 'mod-4', title: 'Signatures numériques et certificats', titleEn: 'Digital signatures and certificates', description: 'Authentification et intégrité', descriptionEN: 'Authentication and integrity', isFree: false, order: 4, duration: '1h30' },
      { id: 'mod-5', title: 'Protocoles cryptographiques', titleEn: 'Cryptographic protocols', description: 'SSL/TLS, IPsec', descriptionEN: 'SSL/TLS, IPsec', isFree: false, order: 5, duration: '2h' },
      { id: 'mod-6', title: 'Applications pratiques en cybersécurité', titleEn: 'Practical applications in cybersecurity', description: 'Cas d\'usage concrets', descriptionEN: 'Concrete use cases', isFree: false, order: 6, duration: '2h' },
      { id: 'mod-7', title: 'TP – Mise en œuvre d\'outils', titleEn: 'Hands-on – Implementing tools', description: 'Chiffrement et hashage en pratique', descriptionEN: 'Encryption and hashing in practice', isFree: false, order: 7, duration: '2h' },
    ]
  },
  {
    id: 'cyber-malware',
    slug: 'analyse-malware',
    category: 'cybersecurite',
    title: 'Analyse de Malware',
    titleEn: 'Malware Analysis',
    description: 'Analyse statique et dynamique des malwares : laboratoire sécurisé, outils professionnels et rédaction de rapports.',
    descriptionEN: 'Static and dynamic malware analysis: secure lab, professional tools and report writing.',
    longDescription: "Apprendre à analyser les logiciels malveillants en utilisant les techniques d'analyse statique et dynamique. L'apprenant sera capable de comprendre le fonctionnement d'un malware, d'évaluer son impact et de définir des méthodes d'éradication appropriées.",
    longDescriptionEN: "Learn to analyze malware using static and dynamic analysis techniques. Learners will understand how malware works, evaluate its impact and define appropriate eradication methods.",
    level: 2,
    price: 99,
    duree_heures: 20,
    image: 'https://images.pexels.com/photos/5380643/pexels-photo-5380643.jpeg?w=800',
    tags: ['cybersecurite', 'malware', 'analyse', 'reverse-engineering'],
    competences: [
      "Mettre en place un environnement d'analyse sécurisé et isolé",
      "Réaliser une analyse statique complète d'un exécutable suspect",
      "Effectuer une analyse dynamique et observer le comportement d'un malware",
      "Utiliser des outils professionnels (IDA Pro, Wireshark, Cuckoo Sandbox)",
      "Identifier les indicateurs de compromission (IOC)",
      "Rédiger un rapport d'analyse de malware professionnel",
      "Comprendre les techniques d'obfuscation et de packing"
    ],
    public_cible: 'Intermédiaire',
    prerequis: 'Connaissances en systèmes d\'exploitation (Windows/Linux), bases de réseaux, notions de programmation',
    modules: [
      { id: 'mod-0', title: 'Introduction à l\'analyse de malware', titleEn: 'Introduction to malware analysis', description: 'Pourquoi et comment', descriptionEN: 'Why and how', isFree: true, order: 0, duration: '1h30' },
      { id: 'mod-1', title: 'Mise en place d\'un laboratoire sécurisé', titleEn: 'Setting up a secure lab', description: 'VM, réseau isolé', descriptionEN: 'VM, isolated network', isFree: false, order: 1, duration: '2h' },
      { id: 'mod-2', title: 'Analyse statique', titleEn: 'Static analysis', description: 'Strings, hex éditeur, format PE', descriptionEN: 'Strings, hex editor, PE format', isFree: false, order: 2, duration: '2h' },
      { id: 'mod-3', title: 'Analyse statique avancée', titleEn: 'Advanced static analysis', description: 'Désassemblage avec IDA Pro', descriptionEN: 'Disassembly with IDA Pro', isFree: false, order: 3, duration: '2h' },
      { id: 'mod-4', title: 'Analyse dynamique', titleEn: 'Dynamic analysis', description: 'RegShot, Capture-BAT, LordPE', descriptionEN: 'RegShot, Capture-BAT, LordPE', isFree: false, order: 4, duration: '2h' },
      { id: 'mod-5', title: 'Analyse réseau des malwares', titleEn: 'Malware network analysis', description: 'Wireshark', descriptionEN: 'Wireshark', isFree: false, order: 5, duration: '2h' },
      { id: 'mod-6', title: 'Sandboxing automatisé', titleEn: 'Automated sandboxing', description: 'Cuckoo Sandbox, Malwr', descriptionEN: 'Cuckoo Sandbox, Malwr', isFree: false, order: 6, duration: '2h' },
      { id: 'mod-7', title: 'Techniques d\'obfuscation et contre-mesures', titleEn: 'Obfuscation techniques and countermeasures', description: 'Packing, anti-debug', descriptionEN: 'Packing, anti-debug', isFree: false, order: 7, duration: '2h' },
      { id: 'mod-8', title: 'Rédaction de rapports d\'analyse', titleEN: 'Writing analysis reports', description: 'Structure et livrables', descriptionEN: 'Structure and deliverables', isFree: false, order: 8, duration: '2h' },
    ]
  },
  {
    id: 'cyber-pentest',
    slug: 'pentesting-introduction',
    category: 'cybersecurite',
    title: 'Pentesting – Introduction et Pratique',
    titleEn: 'Pentesting – Introduction and Practice',
    description: 'Initiation au pentesting : Nmap, Metasploit, Hydra, scans de vulnérabilités et rédaction de rapports.',
    descriptionEN: 'Introduction to pentesting: Nmap, Metasploit, Hydra, vulnerability scanning and report writing.',
    longDescription: "Initier aux techniques de test d'intrusion (pentesting) en utilisant les outils standards du secteur : Nmap, Metasploit et Hydra. L'apprenant apprendra à réaliser un audit de sécurité complet, de la reconnaissance à l'exploitation de vulnérabilités.",
    longDescriptionEN: "Introduce penetration testing techniques using industry-standard tools: Nmap, Metasploit and Hydra. Learners will perform a complete security audit from reconnaissance to vulnerability exploitation.",
    level: 2,
    price: 99,
    duree_heures: 25,
    image: 'https://images.pexels.com/photos/60504/security-hacker-black-background-60504.jpeg?w=800',
    tags: ['cybersecurite', 'pentesting', 'nmap', 'metasploit'],
    competences: [
      "Maîtriser Nmap pour le scanning de ports et la détection de services",
      "Utiliser Metasploit pour exploiter des vulnérabilités connues",
      "Réaliser des attaques par dictionnaire avec Hydra",
      "Mettre en place un laboratoire de pentesting complet (Kali + Metasploitable)",
      "Effectuer des scans de vulnérabilités avec Nessus/OpenVAS",
      "Rédiger un rapport de test d'intrusion professionnel",
      "Comprendre le cadre légal du pentesting"
    ],
    public_cible: 'Intermédiaire',
    prerequis: 'Connaissances en réseaux (TCP/IP, OSI), bases de Linux, notions de cybersécurité',
    modules: [
      { id: 'mod-0', title: 'Introduction au pentesting', titleEn: 'Introduction to pentesting', description: 'Méthodologie et cadre légal', descriptionEN: 'Methodology and legal framework', isFree: true, order: 0, duration: '1h30' },
      { id: 'mod-1', title: 'Découverte et utilisation de Nmap', titleEn: 'Discovering and using Nmap', description: 'Scanning de ports, détection de services', descriptionEN: 'Port scanning, service detection', isFree: false, order: 1, duration: '2h' },
      { id: 'mod-2', title: 'Initiation à Metasploit', titleEn: 'Introduction to Metasploit', description: 'Installation et prise en main', descriptionEN: 'Installation and getting started', isFree: false, order: 2, duration: '2h' },
      { id: 'mod-3', title: 'Exploitation de vulnérabilités avec Metasploit', titleEn: 'Exploiting vulnerabilities with Metasploit', description: 'Metasploitable 2', descriptionEN: 'Metasploitable 2', isFree: false, order: 3, duration: '3h' },
      { id: 'mod-4', title: 'Attaques par dictionnaire et force brute', titleEn: 'Dictionary and brute force attacks', description: 'Hydra', descriptionEN: 'Hydra', isFree: false, order: 4, duration: '2h' },
      { id: 'mod-5', title: 'Connexion Hydra + Nmap + dictionnaire', titleEn: 'Connecting Hydra + Nmap + dictionary', description: 'Workflow complet', descriptionEN: 'Complete workflow', isFree: false, order: 5, duration: '2h' },
      { id: 'mod-6', title: 'Ouvrir une session Meterpreter à distance', titleEn: 'Opening a remote Meterpreter session', description: 'Post-exploitation', descriptionEN: 'Post-exploitation', isFree: false, order: 6, duration: '2h' },
      { id: 'mod-7', title: 'Scan de vulnérabilités avec Nessus et OpenVAS', titleEn: 'Vulnerability scanning with Nessus and OpenVAS', description: 'Sous Kali', descriptionEN: 'On Kali', isFree: false, order: 7, duration: '3h' },
      { id: 'mod-8', title: 'Tests de sécurité d\'un serveur Apache', titleEn: 'Security testing of an Apache server', description: 'Avec curl', descriptionEN: 'With curl', isFree: false, order: 8, duration: '2h' },
      { id: 'mod-9', title: 'Rédaction d\'un rapport de pentest', titleEn: 'Writing a pentest report', description: 'Structure et livrables', descriptionEN: 'Structure and deliverables', isFree: false, order: 9, duration: '2h' },
    ]
  },
  {
    id: 'cyber-hardening-linux',
    slug: 'hardening-linux',
    category: 'cybersecurite',
    title: 'Hardening Linux – Durcissement de Systèmes',
    titleEn: 'Linux Hardening – System Hardening',
    description: 'Durcissement complet de systèmes Linux : noyau, fichiers, SSH, SELinux, HIDS et conformité ANSSI.',
    descriptionEN: 'Complete Linux system hardening: kernel, files, SSH, SELinux, HIDS and ANSSI compliance.',
    longDescription: "Apprendre à durcir (hardening) des systèmes Linux conformément aux recommandations de l'ANSSI. L'apprenant maîtrisera les techniques de sécurisation du noyau, des systèmes de fichiers, de la mémoire, du réseau et des accès sur Debian et autres distributions.",
    longDescriptionEN: "Learn to harden Linux systems in accordance with ANSSI recommendations. Learners will master kernel, filesystem, memory, network and access hardening techniques on Debian and other distributions.",
    level: 2,
    price: 109,
    duree_heures: 25,
    image: 'https://images.pexels.com/photos/1089440/pexels-photo-1089440.jpeg?w=800',
    tags: ['cybersecurite', 'linux', 'hardening', 'anssi'],
    competences: [
      "Durcir un système Linux selon les recommandations ANSSI",
      "Configurer le noyau, GRUB et le démarrage sécurisé (UEFI/Secure Boot)",
      "Mettre en place des politiques de mots de passe robustes",
      "Sécuriser les accès SSH et la gestion des privilèges (sudoers)",
      "Configurer SELinux pour le contrôle d'accès obligatoire",
      "Déployer un HIDS pour la détection d'intrusion",
      "Assurer la journalisation et l'imputabilité des actions",
      "Réaliser un audit de sécurité complet d'un système Linux"
    ],
    public_cible: 'Intermédiaire',
    prerequis: 'Connaissances solides en administration Linux (Debian/Ubuntu), bases de réseaux',
    modules: [
      { id: 'mod-0', title: 'Introduction au hardening Linux', titleEn: 'Introduction to Linux hardening', description: 'Présentation et méthodologie', descriptionEN: 'Presentation and methodology', isFree: true, order: 0, duration: '1h30' },
      { id: 'mod-1', title: 'Configuration du noyau post-installation', titleEn: 'Post-installation kernel configuration', description: 'Sysctl, paramètres kernel', descriptionEN: 'Sysctl, kernel parameters', isFree: false, order: 1, duration: '2h' },
      { id: 'mod-2', title: 'BIOS, démarrage UEFI et Secure Boot', titleEn: 'BIOS, UEFI boot and Secure Boot', description: 'Sécurité du démarrage', descriptionEN: 'Boot security', isFree: false, order: 2, duration: '1h30' },
      { id: 'mod-3', title: 'Configuration de GRUB et protection par mot de passe', titleEn: 'GRUB configuration and password protection', description: 'Sécuriser le bootloader', descriptionEN: 'Securing the bootloader', isFree: false, order: 3, duration: '1h30' },
      { id: 'mod-4', title: 'Durcissement des systèmes de fichiers sous Debian 12', titleEN: 'Filesystem hardening on Debian 12', description: 'Permissions, partitions, options', descriptionEN: 'Permissions, partitions, options', isFree: false, order: 4, duration: '2h' },
      { id: 'mod-5', title: 'Configuration de la mémoire', titleEn: 'Memory configuration', description: 'ASLR, NX bit, protections', descriptionEN: 'ASLR, NX bit, protections', isFree: false, order: 5, duration: '1h30' },
      { id: 'mod-6', title: 'Gestion des mots de passe et politiques de comptes', titleEn: 'Password and account policy management', description: 'Complexité, expiration, verrouillage', descriptionEN: 'Complexity, expiration, lockout', isFree: false, order: 6, duration: '1h30' },
      { id: 'mod-7', title: 'Le fichier sudoers – principe du moindre privilège', titleEn: 'The sudoers file – principle of least privilege', description: 'Gestion des privilèges', descriptionEN: 'Privilege management', isFree: false, order: 7, duration: '1h30' },
      { id: 'mod-8', title: 'Sécurisation des accès SSH', titleEn: 'Securing SSH access', description: 'Clés, configuration, fail2ban', descriptionEN: 'Keys, configuration, fail2ban', isFree: false, order: 8, duration: '2h' },
      { id: 'mod-9', title: 'SELinux – configuration et politiques', titleEn: 'SELinux – configuration and policies', description: 'Contrôle d\'accès obligatoire', descriptionEN: 'Mandatory access control', isFree: false, order: 9, duration: '2h' },
      { id: 'mod-10', title: 'Pare-feu et sécurité réseau', titleEn: 'Firewall and network security', description: 'Iptables, nftables', descriptionEN: 'Iptables, nftables', isFree: false, order: 10, duration: '2h' },
      { id: 'mod-11', title: 'HIDS – détection d\'intrusion', titleEn: 'HIDS – intrusion detection', description: 'AIDE, OSSEC, rkhunter', descriptionEN: 'AIDE, OSSEC, rkhunter', isFree: false, order: 11, duration: '2h' },
      { id: 'mod-12', title: 'Partitionnement sécurisé et LVM', titleEn: 'Secure partitioning and LVM', description: 'Organisation du stockage', descriptionEN: 'Storage organization', isFree: false, order: 12, duration: '1h30' },
      { id: 'mod-13', title: 'Journalisation et imputabilité', titleEN: 'Logging and accountability', description: 'Auditd, syslog, centralisation', descriptionEN: 'Auditd, syslog, centralization', isFree: false, order: 13, duration: '1h30' },
      { id: 'mod-14', title: 'Mises à jour automatiques et gestion des correctifs', titleEn: 'Automatic updates and patch management', description: 'Maintenance de sécurité', descriptionEN: 'Security maintenance', isFree: false, order: 14, duration: '1h30' },
      { id: 'mod-15', title: 'Audit de sécurité et conformité ANSSI', titleEn: 'Security audit and ANSSI compliance', description: 'Vérification et rapport', descriptionEN: 'Verification and report', isFree: false, order: 15, duration: '2h' },
    ]
  },
  {
    id: 'cyber-hardening-windows',
    slug: 'hardening-windows-server',
    category: 'cybersecurite',
    title: 'Hardening Windows Server et Active Directory',
    titleEn: 'Windows Server and Active Directory Hardening',
    description: 'Durcissement Windows Server et Active Directory : sécurité système, IAM, détection d\'attaques et conformité.',
    descriptionEN: 'Windows Server and Active Directory hardening: system security, IAM, attack detection and compliance.',
    longDescription: "Maîtriser le durcissement des environnements Windows Server et Active Directory. Ce cours couvre la sécurité de l'AD, la gestion des identités (IAM), les protocoles d'authentification (NTLM/Kerberos), la détection d'attaques et les mécanismes de défense avancés de Microsoft.",
    longDescriptionEN: "Master the hardening of Windows Server and Active Directory environments. This course covers AD security, identity management (IAM), authentication protocols (NTLM/Kerberos), attack detection and Microsoft's advanced defense mechanisms.",
    level: 2,
    price: 119,
    duree_heures: 30,
    image: 'https://images.pexels.com/photos/114882/pexels-photo-114882.jpeg?w=800',
    tags: ['cybersecurite', 'windows', 'active-directory', 'hardening'],
    competences: [
      "Durcir un environnement Windows Server selon les bonnes pratiques Microsoft et ANSSI",
      "Sécuriser Active Directory (IAM, GPO, stratégies de mot de passe)",
      "Implémenter Device Guard, Credential Guard et WDAC",
      "Configurer Microsoft Defender et l'Exploit Guard",
      "Détecter les attaques par brute force sur l'AD via un SIEM",
      "Sécuriser les protocoles d'authentification NTLM et Kerberos",
      "Centraliser et analyser les journaux de sécurité Windows",
      "Réaliser un audit complet d'un environnement Windows Server"
    ],
    public_cible: 'Intermédiaire à avancé',
    prerequis: 'Connaissances en administration Windows Server, bases d\'Active Directory, notions de cybersécurité',
    modules: [
      { id: 'mod-0', title: 'Tour d\'horizon des risques et méthodologie', titleEn: 'Risk overview and methodology', description: 'Méthodologie de durcissement', descriptionEN: 'Hardening methodology', isFree: true, order: 0, duration: '1h30' },
      { id: 'mod-1', title: 'Gérer un projet de durcissement', titleEn: 'Managing a hardening project', description: 'Planification et déploiement', descriptionEN: 'Planning and deployment', isFree: false, order: 1, duration: '1h30' },
      { id: 'mod-2', title: 'Durcissement hardware', titleEn: 'Hardware hardening', description: 'Secure Boot, TPM, VBS, DMA Protection', descriptionEN: 'Secure Boot, TPM, VBS, DMA Protection', isFree: false, order: 2, duration: '2h' },
      { id: 'mod-3', title: 'Sécurité du système', titleEn: 'System security', description: 'Device Guard, Credential Guard, WDAC', descriptionEN: 'Device Guard, Credential Guard, WDAC', isFree: false, order: 3, duration: '2h' },
      { id: 'mod-4', title: 'Microsoft Defender – configuration avancée', titleEn: 'Microsoft Defender – advanced configuration', description: 'Exploit Guard', descriptionEN: 'Exploit Guard', isFree: false, order: 4, duration: '2h' },
      { id: 'mod-5', title: 'Sécurisation du réseau', titleEn: 'Network security', description: 'Pare-feu, règles ICMP, segmentation', descriptionEN: 'Firewall, ICMP rules, segmentation', isFree: false, order: 5, duration: '2h' },
      { id: 'mod-6', title: 'Durcissement des données', titleEn: 'Data hardening', description: 'BitLocker, EFS, sauvegarde', descriptionEN: 'BitLocker, EFS, backup', isFree: false, order: 6, duration: '1h30' },
      { id: 'mod-7', title: 'Gestion des périphériques et contrôle d\'accès', titleEn: 'Device management and access control', description: 'Restrictions et politiques', descriptionEN: 'Restrictions and policies', isFree: false, order: 7, duration: '1h30' },
      { id: 'mod-8', title: 'Contrôle des applications', titleEn: 'Application control', description: 'AppLocker, WDAC policies', descriptionEN: 'AppLocker, WDAC policies', isFree: false, order: 8, duration: '2h' },
      { id: 'mod-9', title: 'Protection de l\'identité', titleEn: 'Identity protection', description: 'Azure RMS, Intune, MFA', descriptionEN: 'Azure RMS, Intune, MFA', isFree: false, order: 9, duration: '2h' },
      { id: 'mod-10', title: 'Sécurité Active Directory', titleEn: 'Active Directory security', description: 'IAM, OU, groupes de sécurité', descriptionEN: 'IAM, OU, security groups', isFree: false, order: 10, duration: '2h' },
      { id: 'mod-11', title: 'Protocoles d\'authentification NTLM et Kerberos', titleEn: 'NTLM and Kerberos authentication protocols', description: 'Sécurisation', descriptionEN: 'Securing', isFree: false, order: 11, duration: '2h' },
      { id: 'mod-12', title: 'Détection d\'attaques brute force dans l\'AD', titleEn: 'Brute force attack detection in AD', description: 'ELK/SIEM', descriptionEN: 'ELK/SIEM', isFree: false, order: 12, duration: '2h' },
      { id: 'mod-13', title: 'Centralisation des logs avec WEC', titleEn: 'Log centralization with WEC', description: 'Windows Event Collector', descriptionEN: 'Windows Event Collector', isFree: false, order: 13, duration: '1h30' },
      { id: 'mod-14', title: 'Sécurité avec le Cloud', titleEN: 'Cloud security', description: 'Azure, hybridation', descriptionEN: 'Azure, hybridization', isFree: false, order: 14, duration: '2h' },
      { id: 'mod-15', title: 'Bonnes pratiques et conformité ANSSI', titleEN: 'Best practices and ANSSI compliance', description: 'Checklist finale', descriptionEN: 'Final checklist', isFree: false, order: 15, duration: '1h30' },
    ]
  },
  {
    id: 'cyber-hardening-iot',
    slug: 'hardening-iot-cloud',
    category: 'cybersecurite',
    title: 'Hardening IoT et Cloud',
    titleEn: 'IoT and Cloud Hardening',
    description: 'Sécurité IoT et Cloud : segmentation réseau, protection des ports et bonnes pratiques de déploiement.',
    descriptionEN: 'IoT and Cloud security: network segmentation, port protection and deployment best practices.',
    longDescription: "Apprendre à sécuriser les environnements IoT et Cloud. Ce cours couvre la segmentation réseau pour l'IoT, la protection des ports, la sécurisation des communications MQTT et les bonnes pratiques de sécurité pour les déploiements Cloud.",
    longDescriptionEN: "Learn to secure IoT and Cloud environments. This course covers IoT network segmentation, port protection, MQTT communication security and best practices for Cloud deployments.",
    level: 2,
    price: 89,
    duree_heures: 15,
    image: 'https://images.pexels.com/photos/5380643/pexels-photo-5380643.jpeg?w=800',
    tags: ['cybersecurite', 'iot', 'cloud', 'reseaux'],
    competences: [
      "Segmenter un réseau pour isoler les équipements IoT",
      "Configurer la protection des ports sur un switch Cisco",
      "Sécuriser les communications IoT (MQTT, protocoles)",
      "Comprendre les enjeux de sécurité dans le Cloud",
      "Appliquer les bonnes pratiques de sécurité Cloud",
      "Utiliser Cisco Packet Tracer pour la simulation réseau"
    ],
    public_cible: 'Intermédiaire',
    prerequis: 'Connaissances en réseaux (VLAN, routage), notions de Cloud Computing',
    modules: [
      { id: 'mod-0', title: 'Introduction à la sécurité IoT', titleEn: 'Introduction to IoT security', description: 'Enjeux et menaces', descriptionEN: 'Issues and threats', isFree: true, order: 0, duration: '1h30' },
      { id: 'mod-1', title: 'Segmentation LAN pour l\'IoT', titleEn: 'LAN segmentation for IoT', description: 'VLAN, routage inter-VLAN', descriptionEN: 'VLAN, inter-VLAN routing', isFree: false, order: 1, duration: '2h' },
      { id: 'mod-2', title: 'Protection des ports réseau', titleEn: 'Network port protection', description: 'Port Security, Cisco Packet Tracer', descriptionEN: 'Port Security, Cisco Packet Tracer', isFree: false, order: 2, duration: '2h' },
      { id: 'mod-3', title: 'Sécurisation des communications IoT', titleEn: 'Securing IoT communications', description: 'MQTT, chiffrement', descriptionEN: 'MQTT, encryption', isFree: false, order: 3, duration: '2h' },
      { id: 'mod-4', title: 'Introduction à la sécurité Cloud', titleEn: 'Introduction to Cloud security', description: 'Concepts fondamentaux', descriptionEN: 'Fundamental concepts', isFree: false, order: 4, duration: '1h30' },
      { id: 'mod-5', title: 'Modèles de responsabilité partagée', titleEn: 'Shared responsibility models', description: 'IaaS, PaaS, SaaS', descriptionEN: 'IaaS, PaaS, SaaS', isFree: false, order: 5, duration: '1h30' },
      { id: 'mod-6', title: 'Sécurisation des workloads Cloud', titleEn: 'Securing Cloud workloads', description: 'Bonnes pratiques', descriptionEN: 'Best practices', isFree: false, order: 6, duration: '2h' },
      { id: 'mod-7', title: 'TP – Segmentation LAN avec Cisco Packet Tracer', titleEn: 'Hands-on – LAN segmentation with Cisco Packet Tracer', description: 'Simulation réseau', descriptionEN: 'Network simulation', isFree: false, order: 7, duration: '2h' },
    ]
  },
  {
    id: 'cyber-reseaux',
    slug: 'securite-reseaux',
    category: 'cybersecurite',
    title: 'Sécurité des Réseaux',
    titleEn: 'Network Security',
    description: 'Sécurité réseau complète : firewall, IDS/IPS, VPN, proxy, Wireshark, Nmap, DMZ et PSSI.',
    descriptionEN: 'Complete network security: firewall, IDS/IPS, VPN, proxy, Wireshark, Nmap, DMZ and PSSI.',
    longDescription: "Maîtriser les concepts et outils de la sécurité réseau. De la détection des menaces à la mise en œuvre de défenses (firewall, IDS/IPS, VPN, proxy, Wireshark), ce cours forme des professionnels capables de concevoir et sécuriser une infrastructure réseau d'entreprise.",
    longDescriptionEN: "Master the concepts and tools of network security. From threat detection to implementing defenses (firewall, IDS/IPS, VPN, proxy, Wireshark), this course trains professionals capable of designing and securing enterprise network infrastructure.",
    level: 2,
    price: 119,
    duree_heures: 30,
    image: 'https://images.pexels.com/photos/114882/pexels-photo-114882.jpeg?w=800',
    tags: ['cybersecurite', 'reseaux', 'firewall', 'vpn', 'ids'],
    competences: [
      "Identifier et analyser les menaces et vulnérabilités réseau",
      "Mettre en œuvre des firewalls (PfSense) et des IDS/IPS",
      "Configurer des VPN sécurisés (IPsec, OpenVPN)",
      "Analyser le trafic réseau avec Wireshark",
      "Réaliser des scans de sécurité avec Nmap",
      "Concevoir et sécuriser une DMZ",
      "Mettre en place un proxy et du filtrage web",
      "Élaborer une PSSI (Politique de Sécurité des SI)",
      "Sécuriser les réseaux Wi-Fi d'entreprise"
    ],
    public_cible: 'Intermédiaire',
    prerequis: 'Connaissances solides en réseaux (CCNA ou équivalent), bases de TCP/IP',
    modules: [
      { id: 'mod-0', title: 'Introduction à la sécurité des réseaux', titleEn: 'Introduction to network security', description: 'Concepts fondamentaux', descriptionEN: 'Fundamental concepts', isFree: true, order: 0, duration: '1h30' },
      { id: 'mod-1', title: 'Comprendre les menaces réseau', titleEn: 'Understanding network threats', description: 'DDoS, intrusion, malware', descriptionEN: 'DDoS, intrusion, malware', isFree: false, order: 1, duration: '2h' },
      { id: 'mod-2', title: 'Sécurité des accès – NAC', titleEn: 'Access security – NAC', description: 'Contrôle d\'accès réseau et authentification', descriptionEN: 'Network access control and authentication', isFree: false, order: 2, duration: '2h' },
      { id: 'mod-3', title: 'Sécurité des données', titleEn: 'Data security', description: 'Cryptage, stockage sécurisé, sauvegarde', descriptionEN: 'Encryption, secure storage, backup', isFree: false, order: 3, duration: '1h30' },
      { id: 'mod-4', title: 'Sécurité des échanges', titleEn: 'Exchange security', description: 'SSL/TLS, HTTPS, sécurisation des API', descriptionEN: 'SSL/TLS, HTTPS, API security', isFree: false, order: 4, duration: '2h' },
      { id: 'mod-5', title: 'Firewalls et PfSense', titleEn: 'Firewalls and PfSense', description: 'Configuration et déploiement', descriptionEN: 'Configuration and deployment', isFree: false, order: 5, duration: '2h' },
      { id: 'mod-6', title: 'IDS/IPS', titleEn: 'IDS/IPS', description: 'Détection et prévention d\'intrusion', descriptionEN: 'Intrusion detection and prevention', isFree: false, order: 6, duration: '2h' },
      { id: 'mod-7', title: 'VPN', titleEn: 'VPN', description: 'Conception et déploiement (IPsec, OpenVPN)', descriptionEN: 'Design and deployment (IPsec, OpenVPN)', isFree: false, order: 7, duration: '2h' },
      { id: 'mod-8', title: 'Proxy et filtrage web', titleEn: 'Proxy and web filtering', description: 'Squid, SquidGuard', descriptionEN: 'Squid, SquidGuard', isFree: false, order: 8, duration: '1h30' },
      { id: 'mod-9', title: 'Analyse réseau avec Wireshark', titleEn: 'Network analysis with Wireshark', description: 'Capture et analyse de paquets', descriptionEN: 'Packet capture and analysis', isFree: false, order: 9, duration: '2h' },
      { id: 'mod-10', title: 'Scanning réseau avec Nmap', titleEn: 'Network scanning with Nmap', description: 'Techniques de scan', descriptionEN: 'Scan techniques', isFree: false, order: 10, duration: '1h30' },
      { id: 'mod-11', title: 'DMZ', titleEn: 'DMZ', description: 'Conception et sécurisation', descriptionEN: 'Design and security', isFree: false, order: 11, duration: '1h30' },
      { id: 'mod-12', title: 'Haute disponibilité et sécurité', titleEn: 'High availability and security', description: 'Redondance et résilience', descriptionEN: 'Redundancy and resilience', isFree: false, order: 12, duration: '1h30' },
      { id: 'mod-13', title: 'Sécurité Wi-Fi', titleEn: 'Wi-Fi security', description: 'WPA2/WPA3, evil twin, rogue AP', descriptionEN: 'WPA2/WPA3, evil twin, rogue AP', isFree: false, order: 13, duration: '2h' },
      { id: 'mod-14', title: 'ACL – listes de contrôle d\'accès', titleEn: 'ACL – access control lists', description: 'Filtrage et sécurité', descriptionEN: 'Filtering and security', isFree: false, order: 14, duration: '1h30' },
      { id: 'mod-15', title: 'DLP – prévention de la perte de données', titleEn: 'DLP – data loss prevention', description: 'Stratégies et outils', descriptionEN: 'Strategies and tools', isFree: false, order: 15, duration: '1h30' },
      { id: 'mod-16', title: 'PSSI', titleEn: 'PSSI', description: 'Politique de sécurité des systèmes d\'information', descriptionEN: 'Information systems security policy', isFree: false, order: 16, duration: '1h30' },
      { id: 'mod-17', title: 'SOC – Security Operations Center', titleEn: 'SOC – Security Operations Center', description: 'Organisation et processus', descriptionEN: 'Organization and processes', isFree: false, order: 17, duration: '2h' },
      { id: 'mod-18', title: 'Spanning Tree et sécurité de couche 2', titleEn: 'Spanning Tree and layer 2 security', description: 'Protection du réseau local', descriptionEN: 'Local network protection', isFree: false, order: 18, duration: '1h30' },
    ]
  },
  {
    id: 'cyber-kali',
    slug: 'kali-linux-outils',
    category: 'cybersecurite',
    title: 'Kali Linux – Outils et Pratiques',
    titleEn: 'Kali Linux – Tools and Practices',
    description: 'Maîtrise de Kali Linux : outils de pentesting, Metasploit, SET, scans de vulnérabilités et travaux pratiques.',
    descriptionEN: 'Mastering Kali Linux: pentesting tools, Metasploit, SET, vulnerability scanning and hands-on exercises.',
    longDescription: "Maîtriser l'utilisation de Kali Linux comme plateforme de test de sécurité. L'apprenant apprendra à installer, configurer et utiliser les principaux outils de Kali pour le pentesting, l'analyse de vulnérabilités et l'ingénierie sociale.",
    longDescriptionEN: "Master the use of Kali Linux as a security testing platform. Learners will install, configure and use Kali's main tools for pentesting, vulnerability analysis and social engineering.",
    level: 2,
    price: 99,
    duree_heures: 20,
    image: 'https://images.pexels.com/photos/60504/security-hacker-black-background-60504.jpeg?w=800',
    tags: ['cybersecurite', 'kali', 'pentesting', 'outils'],
    competences: [
      "Installer et configurer Kali Linux en environnement professionnel",
      "Utiliser les principaux outils de pentesting de Kali",
      "Réaliser des scans de vulnérabilités avec Nessus et OpenVAS",
      "Mettre en œuvre des attaques d'ingénierie sociale avec SET",
      "Exploiter des vulnérabilités avec Metasploit sur Metasploitable",
      "Comprendre le cadre légal de l'utilisation des outils offensifs"
    ],
    public_cible: 'Intermédiaire',
    prerequis: 'Connaissances en Linux, bases de réseaux et de cybersécurité',
    modules: [
      { id: 'mod-0', title: 'Introduction à Kali Linux', titleEn: 'Introduction to Kali Linux', description: 'Installation et configuration', descriptionEN: 'Installation and configuration', isFree: true, order: 0, duration: '1h30' },
      { id: 'mod-1', title: 'Prise en main de l\'environnement', titleEn: 'Getting started with the environment', description: 'Outils de base', descriptionEN: 'Basic tools', isFree: false, order: 1, duration: '1h30' },
      { id: 'mod-2', title: 'Problèmes courants sous Kali Linux', titleEn: 'Common issues on Kali Linux', description: 'Résolution', descriptionEN: 'Resolution', isFree: false, order: 2, duration: '1h' },
      { id: 'mod-3', title: 'Outils de scan et de reconnaissance', titleEn: 'Scanning and reconnaissance tools', description: 'Nmap, Nessus', descriptionEN: 'Nmap, Nessus', isFree: false, order: 3, duration: '2h' },
      { id: 'mod-4', title: 'Metasploit – installation et utilisation avancée', titleEn: 'Metasploit – installation and advanced use', description: 'Exploitation', descriptionEN: 'Exploitation', isFree: false, order: 4, duration: '2h' },
      { id: 'mod-5', title: 'Attaques par force brute', titleEn: 'Brute force attacks', description: 'Hydra, dictionnaires', descriptionEN: 'Hydra, dictionaries', isFree: false, order: 5, duration: '2h' },
      { id: 'mod-6', title: 'Social Engineering Toolkit', titleEn: 'Social Engineering Toolkit', description: 'SET – techniques d\'attaque', descriptionEN: 'SET – attack techniques', isFree: false, order: 6, duration: '2h' },
      { id: 'mod-7', title: 'OpenVAS – scan de vulnérabilités', titleEn: 'OpenVAS – vulnerability scanning', description: 'Configuration et analyse', descriptionEN: 'Configuration and analysis', isFree: false, order: 7, duration: '2h' },
      { id: 'mod-8', title: 'TP – Kali contre Metasploitable 2', titleEn: 'Hands-on – Kali vs Metasploitable 2', description: 'VSFTPD, Meterpreter', descriptionEN: 'VSFTPD, Meterpreter', isFree: false, order: 8, duration: '3h' },
      { id: 'mod-9', title: 'Bonnes pratiques et cadre légal', titleEn: 'Best practices and legal framework', description: 'Utilisation responsable', descriptionEN: 'Responsible use', isFree: false, order: 9, duration: '1h' },
    ]
  },
  {
    id: 'cyber-rgpd',
    slug: 'cnil-rgpd-aspects-juridiques',
    category: 'cybersecurite',
    title: 'CNIL, RGPD et Aspects Juridiques du Hacking',
    titleEn: 'CNIL, GDPR and Legal Aspects of Hacking',
    description: 'Cadre juridique de la cybersécurité : RGPD, CNIL, lois hacking et obligations légales des professionnels.',
    descriptionEN: 'Cybersecurity legal framework: GDPR, CNIL, hacking laws and legal obligations of professionals.',
    longDescription: "Comprendre le cadre juridique de la cybersécurité en France et en Europe. Ce cours couvre le RGPD, le rôle de la CNIL, les lois relatives au hacking et les obligations légales des professionnels de la sécurité.",
    longDescriptionEN: "Understand the legal framework of cybersecurity in France and Europe. This course covers GDPR, the role of CNIL, hacking laws and legal obligations of security professionals.",
    level: 1,
    price: 39,
    duree_heures: 10,
    image: 'https://images.pexels.com/photos/5380643/pexels-photo-5380643.jpeg?w=800',
    tags: ['cybersecurite', 'rgpd', 'cnil', 'juridique'],
    competences: [
      "Comprendre le rôle et les pouvoirs de la CNIL",
      "Maîtriser les principes fondamentaux du RGPD",
      "Connaître les lois françaises relatives au hacking",
      "Identifier les obligations légales en cas de violation de données",
      "Appliquer le cadre juridique lors d'un test de sécurité",
      "Rédiger des clauses de conformité RGPD"
    ],
    public_cible: 'Débutant à intermédiaire',
    prerequis: 'Aucun – accessible aux professionnels IT souhaitant comprendre le cadre légal',
    modules: [
      { id: 'mod-0', title: 'Introduction au cadre juridique', titleEn: 'Introduction to the legal framework', description: 'Cybersécurité et droit', descriptionEN: 'Cybersecurity and law', isFree: true, order: 0, duration: '1h' },
      { id: 'mod-1', title: 'La CNIL – rôle, missions et pouvoirs', titleEn: 'CNIL – role, missions and powers', description: 'L\'autorité de contrôle', descriptionEN: 'The control authority', isFree: false, order: 1, duration: '1h30' },
      { id: 'mod-2', title: 'Le RGPD – principes, droits, obligations', titleEn: 'GDPR – principles, rights, obligations', description: 'Protection des données', descriptionEN: 'Data protection', isFree: false, order: 2, duration: '1h30' },
      { id: 'mod-3', title: 'Les lois relatives au hacking', titleEn: 'Hacking-related laws', description: 'Articles 323-1 à 323-7 du Code pénal', descriptionEN: 'Articles 323-1 to 323-7 of the Penal Code', isFree: false, order: 3, duration: '1h30' },
      { id: 'mod-4', title: 'Cadre légal du pentesting', titleEn: 'Legal framework for pentesting', description: 'Tests de sécurité et légalité', descriptionEN: 'Security testing and legality', isFree: false, order: 4, duration: '1h' },
      { id: 'mod-5', title: 'Obligation de notification des violations', titleEn: 'Obligation to report violations', description: '72h et procédures', descriptionEN: '72h and procedures', isFree: false, order: 5, duration: '1h' },
      { id: 'mod-6', title: 'Responsabilités juridiques', titleEn: 'Legal responsibilities', description: 'Professionnels de la sécurité', descriptionEN: 'Security professionals', isFree: false, order: 6, duration: '1h' },
      { id: 'mod-7', title: 'Exercices pratiques', titleEn: 'Practical exercises', description: 'CNIL et RGPD', descriptionEN: 'CNIL and GDPR', isFree: false, order: 7, duration: '1h' },
    ]
  },
  {
    id: 'cyber-avance',
    slug: 'securite-secours-avancee',
    category: 'cybersecurite',
    title: 'Sécurité Avancée – SOC, Gouvernance et Défense',
    titleEn: 'Advanced Security – SOC, Governance and Defense',
    description: 'Sécurité avancée : SOC, NIST CSF, gouvernance, VBS, EMS/Intune et audit de sécurité Windows.',
    descriptionEN: 'Advanced security: SOC, NIST CSF, governance, VBS, EMS/Intune and Windows security audit.',
    longDescription: "Acquérir les compétences avancées en sécurité opérationnelle : gestion d'un SOC, framework NIST, gouvernité de la sécurité, gestion des identités d'entreprise (EMS/Intune) et stratégies de défense globales.",
    longDescriptionEN: "Acquire advanced operational security skills: SOC management, NIST framework, security governance, enterprise identity management (EMS/Intune) and global defense strategies.",
    level: 3,
    price: 149,
    duree_heures: 20,
    image: 'https://images.pexels.com/photos/60504/security-hacker-black-background-60504.jpeg?w=800',
    tags: ['cybersecurite', 'avance', 'soc', 'gouvernance', 'nist'],
    competences: [
      "Comprendre le fonctionnement et l'organisation d'un SOC",
      "Appliquer le NIST Cybersecurity Framework",
      "Mettre en œuvre des contrôles de sécurité conformes aux standards",
      "Gérer la mobilité d'entreprise avec EMS/Intune",
      "Configurer la sécurité basée sur la virtualisation (VBS)",
      "Réaliser un audit de sécurité Windows complet",
      "Élaborer une stratégie de gouvernance sécurité"
    ],
    public_cible: 'Avancé',
    prerequis: 'Expérience en administration Windows, connaissance de la cybersécurité, notions de gouvernance IT',
    modules: [
      { id: 'mod-0', title: 'Le Security Operations Center (SOC)', titleEn: 'The Security Operations Center (SOC)', description: 'Organisation et processus', descriptionEN: 'Organization and processes', isFree: true, order: 0, duration: '1h30' },
      { id: 'mod-1', title: 'Le NIST Cybersecurity Framework', titleEn: 'The NIST Cybersecurity Framework', description: 'CSF – identification, protection, détection, réponse, récupération', descriptionEN: 'CSF – identify, protect, detect, respond, recover', isFree: false, order: 1, duration: '2h' },
      { id: 'mod-2', title: 'Security Controls', titleEn: 'Security Controls', description: 'Contrôles de sécurité et conformité', descriptionEN: 'Security controls and compliance', isFree: false, order: 2, duration: '2h' },
      { id: 'mod-3', title: 'Gouvernance de la sécurité', titleEn: 'Security governance', description: 'Pilotage et stratégie', descriptionEN: 'Management and strategy', isFree: false, order: 3, duration: '2h' },
      { id: 'mod-4', title: 'Enterprise Mobility Security', titleEn: 'Enterprise Mobility Security', description: 'EMS et Microsoft Intune', descriptionEN: 'EMS and Microsoft Intune', isFree: false, order: 4, duration: '2h' },
      { id: 'mod-5', title: 'Windows-as-a-Service', titleEn: 'Windows-as-a-Service', description: 'Gestion des mises à jour de sécurité', descriptionEN: 'Security update management', isFree: false, order: 5, duration: '1h30' },
      { id: 'mod-6', title: 'Virtualization-Based Security', titleEn: 'Virtualization-Based Security', description: 'VBS et System Guard', descriptionEN: 'VBS and System Guard', isFree: false, order: 6, duration: '2h' },
      { id: 'mod-7', title: 'Root of Trust et PC Secured-Core', titleEn: 'Root of Trust and PC Secured-Core', description: 'Sécurité matérielle', descriptionEN: 'Hardware security', isFree: false, order: 7, duration: '1h30' },
      { id: 'mod-8', title: 'Windows Defender Security Center', titleEn: 'Windows Defender Security Center', description: 'Configuration avancée', descriptionEN: 'Advanced configuration', isFree: false, order: 8, duration: '2h' },
      { id: 'mod-9', title: 'Audit Windows', titleEn: 'Windows audit', description: 'Méthodologie et outils', descriptionEN: 'Methodology and tools', isFree: false, order: 9, duration: '2h' },
    ]
  },
];

export function getCourseBySlug(slug: string): Course | undefined {
  return courses.find(c => c.slug === slug);
}

export function getCoursesByLevel(level: 1 | 2 | 3): Course[] {
  return courses.filter(c => c.level === level);
}

export function getCoursesByCategory(category: string): Course[] {
  return courses.filter(c => c.category === category);
}

export const bundles = [
  {
    id: 'bundle-1-2',
    name: 'Pack LVL1 + LVL2',
    nameEn: 'Pack LVL1 + LVL2',
    description: 'Formations Niveau 1 et 2',
    descriptionEn: 'Level 1 and 2 courses',
    price: 119,
    levels: [1, 2],
  },
  {
    id: 'all-access',
    name: 'Pass All Access',
    nameEn: 'All Access Pass',
    description: 'Acces a toutes les formations',
    descriptionEn: 'Access to all courses',
    price: 249,
    levels: [1, 2, 3],
  },
  {
    id: 'cybersecurite-pack',
    name: 'Pack Cybersécurité Complet',
    nameEn: 'Complete Cybersecurity Pack',
    description: 'Les 13 formations cybersécurité',
    descriptionEN: 'All 13 cybersecurity courses',
    price: 499,
    levels: [1, 2, 3],
  },
];
